baseurl = ""
languageCode = "en-us"
theme = "hugo-theme-stack"
paginate = 5
title = "SnufflePuff"
disqusShortname = "hugo-theme-stack"
DefaultContentLanguage = "en"

[permalinks]
post = "/p/:slug/"
page = "/:slug/"

[params]
mainSections = [ "post" ]
featuredImageField = "image"
rssFullContent = true

  [params.footer]
  since = 2_020

  [params.dateFormat]
  published = "Jan 02, 2006"
  lastUpdated = "Jan 02, 2006 15:04 MST"

  [params.sidebar]
  # emoji = "🍥"

    [params.sidebar.avatar]
    local = true
    src = "img/fms.png"

  [params.article]
  math = true
  toc = true

    [params.article.license]
    enabled = true
    default = "Licensed under CC BY-NC-SA 4.0"

  [params.comments]
  enabled = true
  provider = "disqus"

    [params.comments.utterances]
    issueTerm = "pathname"

    [params.comments.remark42]

    [params.comments.vssue]
    autoCreateIssue = false

    [params.comments.waline]
    emoji = [ "https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo" ]
    requiredMeta = [ "name", "email", "url" ]

      [params.comments.waline.locale]
      admin = "Admin"

  [params.widgets]
  enabled = [ "archives", "tag-cloud" ]

    [params.widgets.archives]
    limit = 5

    [params.widgets.tagCloud]
    limit = 10

[params.opengraph.twitter]
card = "summary_large_image"

[params.defaultImage.opengraph]
enabled = false
local = false

  [params.colorScheme]
  toggle = true
  default = "auto"

[params.imageProcessing.cover]
enabled = true

[params.imageProcessing.content]
enabled = true

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = -100
pre = "home"

[related]
includeNewer = true
threshold = 60
toLower = false

  [[related.indices]]
  name = "tags"
  weight = 100

  [[related.indices]]
  name = "categories"
  weight = 200

[markup.tableOfContents]
endLevel = 4
ordered = true
startLevel = 2

[markup.highlight]
noClasses = false
